pip install selenium
pip install robotframework
pip install robotframework-pabot
pip install robotframework-screencaplibrary
pip install robotframework-crypto
pip install robotframework-databaselibrary
pip install robotframework-datadriver
pip install robotframework-dependencylibrary
pip install robotframework-excel
pip install robotframework-excellibrary-xwfintech
pip install robotframework-extendedrequestslibrary
pip install robotframework-jenkins
pip install robotframework-jmeterlibrary
pip install robotframework-jsonlibrary
pip install robotframework-mobilelibrary
pip install robotframework-pabot
pip install robotframework-pythonlibcore
pip install robotframework-requests
pip install robotframework-seleniumlibrary
pip install robotframework-rpa
pip install webdriver-manager
pip install openpyxl
pip install requests
pip install rpaframework
pip install rpaframework-excel
pip install rpa